# Generated by Django 5.2.15 on 2026-06-13 05:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('squat', '深蹲 (Squat)'), ('pushup', '俯卧撑 (Push-up)'), ('plank', '平板支撑 (Plank)')], max_length=20, verbose_name='动作类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='训练时间')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='训练时长(秒)')),
                ('rep_count', models.IntegerField(default=0, verbose_name='完成次数')),
                ('accuracy_score', models.FloatField(default=0.0, verbose_name='动作标准度评分')),
                ('avg_heart_rate', models.FloatField(blank=True, null=True, verbose_name='平均心率(BPM)')),
                ('avg_spo2', models.FloatField(blank=True, null=True, verbose_name='平均血氧(%)')),
                ('training_note', models.TextField(blank=True, null=True, verbose_name='训练随笔')),
                ('error_summary', models.TextField(blank=True, null=True, verbose_name='动作违规日志')),
            ],
            options={
                'verbose_name': '训练记录',
                'verbose_name_plural': '训练记录',
                'db_table': 'training_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('squat', '深蹲'), ('lunge', '弓箭步'), ('push_up', '俯卧撑'), ('core', '核心训练')], max_length=50, verbose_name='运动类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.IntegerField(verbose_name='运动时长(秒)')),
                ('calories', models.IntegerField(default=0, verbose_name='消耗热量(kcal)')),
                ('total_reps', models.IntegerField(default=0, verbose_name='总动作次数')),
                ('avg_accuracy_score', models.FloatField(default=0.0, verbose_name='平均动作标准度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_level', models.CharField(choices=[('EXCELLENT', '优秀'), ('GOOD', '良好'), ('FAIR', '及格'), ('POOR', '需改进')], max_length=20, verbose_name='综合评价等级')),
                ('suggestion_text', models.TextField(verbose_name='AI改进建议')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='pages.activity')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='O', max_length=1, verbose_name='性别')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='身高(cm)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重(kg)')),
                ('hr_max', models.IntegerField(default=190, verbose_name='最大心率')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_offset', models.IntegerField(verbose_name='相对开始时间的偏移(秒)')),
                ('pose_score', models.FloatField(blank=True, null=True, verbose_name='当前秒动作得分')),
                ('current_rep_count', models.IntegerField(default=0, verbose_name='当前累计次数')),
                ('joints_data', models.JSONField(blank=True, null=True, verbose_name='关节坐标帧数据')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='pages.activity')),
            ],
            options={
                'ordering': ['timestamp_offset'],
                'indexes': [models.Index(fields=['activity', 'timestamp_offset'], name='pages_activ_activit_615b2e_idx')],
            },
        ),
    ]
