# Generated by Django 5.2.15 on 2026-07-03 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_mode', models.CharField(choices=[('GUIDED', '引导计划模式'), ('FREE', '自由训练模式')], default='FREE', max_length=20, verbose_name='训练模式')),
                ('activity_type', models.CharField(choices=[('squat', '深蹲 (Squat)'), ('lunge', '弓箭步 (Lunge)'), ('push_up', '俯卧撑 (Push-up)'), ('plank', '平板支撑 (Plank)'), ('mixed_plan', '混合计划 (引导模式)')], max_length=50, verbose_name='运动类型')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('duration', models.IntegerField(default=0, verbose_name='总耗时(秒)')),
                ('total_reps', models.IntegerField(default=0, verbose_name='总次数')),
                ('intensity', models.CharField(choices=[('LOW', '低强度'), ('MED', '中强度'), ('HIGH', '高强度')], default='MED', max_length=10, verbose_name='客观训练强度')),
                ('perceived_exertion', models.IntegerField(default=3, verbose_name='主观感受RPE(1-5级)')),
                ('quality_score', models.IntegerField(default=5, verbose_name='AI质量评分(1-10)')),
                ('calories', models.IntegerField(default=0, verbose_name='消耗热量(kcal)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_records',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='大模型文字评语')),
                ('next_step_suggestion', models.TextField(verbose_name='后续计划优化建议')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='pages.activity')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否为当前执行计划')),
                ('plan_type', models.CharField(choices=[('LLM_GENERATED', '大模型生成'), ('USER_CUSTOM', '用户自定义')], default='LLM_GENERATED', max_length=50, verbose_name='计划类型')),
                ('plan_content', models.JSONField(verbose_name='结构化计划详情JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='O', max_length=1, verbose_name='性别')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='身高(cm)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重(kg)')),
                ('hr_max', models.IntegerField(default=190, verbose_name='最大心率')),
                ('face_feature_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='绑定的特征向量ID(用于人脸登录)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_offset', models.IntegerField(verbose_name='相对开始时间的偏移(秒)')),
                ('phase', models.CharField(choices=[('REST', '组间休息'), ('END', '训练结束')], default='REST', max_length=10, verbose_name='数据来源相位')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='瞬时心率(BPM)')),
                ('spo2', models.FloatField(blank=True, null=True, verbose_name='瞬时血氧(%)')),
                ('current_rep_count', models.IntegerField(default=0, verbose_name='当前累计次数')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='pages.activity')),
            ],
            options={
                'ordering': ['timestamp_offset'],
                'indexes': [models.Index(fields=['activity', 'timestamp_offset'], name='pages_activ_activit_615b2e_idx')],
            },
        ),
    ]
