# Generated by Django 5.2.15 on 2026-06-13 05:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_offset', models.IntegerField(verbose_name='相对开始时间的偏移(秒)')),
                ('error_code', models.IntegerField(verbose_name='错误代码 (如101)')),
                ('error_msg', models.CharField(max_length=255, verbose_name='错误描述')),
            ],
        ),
        migrations.DeleteModel(
            name='TrainingRecord',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_heart_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='平均心率(BPM)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_spo2',
            field=models.FloatField(blank=True, null=True, verbose_name='平均血氧(%)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='training_note',
            field=models.TextField(blank=True, null=True, verbose_name='训练随笔'),
        ),
        migrations.AddField(
            model_name='activitytimeseries',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='瞬时心率(BPM)'),
        ),
        migrations.AddField(
            model_name='activitytimeseries',
            name='spo2',
            field=models.FloatField(blank=True, null=True, verbose_name='瞬时血氧(%)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('squat', '深蹲 (Squat)'), ('lunge', '弓箭步 (Lunge)'), ('push_up', '俯卧撑 (Push-up)'), ('plank', '平板支撑 (Plank)')], max_length=50, verbose_name='运动类型'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='运动时长(秒)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity_records',
        ),
        migrations.AddField(
            model_name='actionerrorlog',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='pages.activity'),
        ),
    ]
