# Generated by Django 5.2.15 on 2026-07-03 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_actionerrorlog_delete_trainingrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='intensity',
            field=models.CharField(choices=[('LOW', '低强度'), ('MED', '中强度'), ('HIGH', '高强度')], default='MED', max_length=10, verbose_name='训练强度'),
        ),
        migrations.AddField(
            model_name='activity',
            name='quality_score',
            field=models.IntegerField(default=5, verbose_name='训练效果质量 (1-10)'),
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前执行中的计划')),
                ('plan_content', models.JSONField(verbose_name='一周计划详情JSON')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
