# Generated by Django 5.2.15 on 2026-07-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_userfaceembedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='会话ID')),
                ('mode', models.CharField(default='free', max_length=20, verbose_name='训练模式')),
                ('exercises', models.JSONField(default=list, verbose_name='动作列表')),
                ('sets', models.IntegerField(default=1, verbose_name='组数')),
                ('reps', models.IntegerField(default=1, verbose_name='每组次数')),
                ('rest_sec', models.IntegerField(default=45, verbose_name='组间休息秒数')),
                ('intensity', models.CharField(default='medium', max_length=20, verbose_name='训练强度')),
                ('status', models.CharField(choices=[('RUNNING', '进行中'), ('FINISHED', '已结束')], default='RUNNING', max_length=20, verbose_name='会话状态')),
                ('phase', models.CharField(choices=[('WORK', '运动中'), ('REST', '组间休息'), ('END', '训练结束')], default='WORK', max_length=10, verbose_name='当前阶段')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('final_reps', models.IntegerField(default=0, verbose_name='最终次数')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_sessions', to='pages.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
