# Generated by Django 5.2.15 on 2026-07-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userprofile_phone_avatar_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
